import type { Metadata } from 'next'
import { Sora } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/navbar'
import Footer from '@/components/footer'
import { cn } from '@/lib/utils'

const inter = Sora({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en' className='dark'>
			<body className={cn(inter.className, 'min-h-screen')}>
				<Navbar />
				{children}
				<Footer />
			</body>
		</html>
	)
}
